### PR TITLE
Check total count during transfer dialog

### PR DESCRIPTION
**Pull request by lifeiscontent**
@nicoschmitt This checks the total count of the current Pokemon you are considering transferring.

### CODE REVIEW

**Comment by niicojs** [comment]
Sorry I was just waiting on basically the same thing. Could you update from master and check what I did and modiy it accordingly is necessary?

**Comment by lifeiscontent** [comment]
@nicoschmitt not sure what you want me to do here... Do you like my implementation better and you think we should use it? Or... what?

**Comment by niicojs** [comment]
Check what I did and tell me if it's good for you. If not submit a updated pr.

**Comment by lifeiscontent** [comment]
@nicoschmitt my implementation is less code, but its up to you. Both work.

**Comment by niicojs** [comment]
fair enough, I did mix both, thanks!

**Pull request closed without merging**
