### PR TITLE
Add more stats to pokemon list UI

### PR DESCRIPTION
**Pull request by lifeiscontent**
This adds the STA, ATK, DEF, and HP stats to each pokemon in the pokemon list.

### CODE REVIEW

**Comment by niicojs** [comment]
Could you please resolve conflicts?

**Comment by lifeiscontent** [comment]
@nicoschmitt sure, should I be merging from master or gh-pages? it looks like your main branch is gh-pages or if its not, you haven't pushed to master in awhile.

**Comment by niicojs** [comment]
Gh-pages is the main branch

**Comment by lifeiscontent** [comment]
@nicoschmitt updated.

**Pull request merged**
